### ISSUE TITLE
Per MS, Control is causing View Name to not fully render when going back to a view from a record that has the Control

### ISSUE THREAD

**Issue by iozm** [a33ik/CompositeAddress_PCF#14]
We were having issues with view names not displaying correctly, we didn't know what was causing it so we just submitted a ticket with MS. 

![image](https://user-images.githubusercontent.com/69154445/93503324-7efa1180-f8dd-11ea-9737-6694e8e1c16c.png)

MS came back with results from their product team as follows: 

> This issue is caused by Composite Address Control in the field Address 1 in the contact form. 
Removing or selecting Text Box(default) resolve the issue 
Is Composite Address Control a 3rd party control? 
>
>I have tested in your organization, and it seems to be resolved the issue.
>
>Here are the repro steps 
>
>1-	Navigate to Customization > customize the system 
>2-	Expand entities and select Contact 
>3-	Select the contact form 
>4-	Dclick the field Address1 
>5-	Select control
>6-	Either remove Composite Address Control or select the default text box 
>
>So if you have this Composite Address Control added in any other entity it will behave the same. 
>
>We Recommend contact the 3rd party control developers so they can modify the CSS for their AB.ConpositeAddress 
>The CSS attribute that causing the issue is this below 
>
![image](https://user-images.githubusercontent.com/69154445/93503776-2e36e880-f8de-11ea-875c-780e0aad1927.png)

Anyone else experienced this before?

**Comment by tgiard2020** [comment]
Our organization is experiencing this same issue. Any help fixing would be greatly appreciated. Thanks!

**Comment by AndrewButenko** [comment]
Hello,
I don't plan to invest my time in this control because I created better version of it. It's available in my PCF controls toolkit and you can download it here - https://github.com/AndrewButenko/ABControlsToolkit
Thanks,
Andrew

**Comment by tgiard2020** [comment]
Thank you!! I imported the new version and that fixed the issue.
