### ISSUE TITLE
Address Formatting

### ISSUE THREAD

**Issue by nerdscripter** [a33ik/CompositeAddress_PCF#2]
Hi Andrew,

I am not able to understand what value is required for Address Pattern, Is it a regex expression or something else ?

**Comment by AndrewButenko** [comment]
I have to provide documentation but generally speaking it's the format that will be used for your resulting address and it has couple of placeholders that will be replaced with values from correspond fields. Here are those placeholders:

{street1}
{street2}
{street3}
{city}
{county}
{state}
{country}
{zipcode}

Also I have special combination like \n that will be replaced with the new line. Here is an example:

When you have format {street1}\n{city} {state}, {zipcode}\n{country} as a result of formatting you'll get following address:

1 Microsoft Way
Redmond WA, 98052
USA

Feel free to update the issue if you have question or close it if everything is clear.

**Comment by AndrewButenko** [comment]
@nerdscripter I'm closing the issue if you have no questions.

**Comment by nerdscripter** [comment]
@AndrewButenko Thanks a lot for the help. It works perfectly now.
