### ISSUE TITLE
some single.text fields are not visible in PCF customization

### ISSUE THREAD

**Issue by SyvokonSergey** [a33ik/CompositeAddress_PCF#3]
Hi Andrew,
All works fine, great job!
But still, have a quick question - any possible reason why some single.text fields are not visible in PCF customization? (Ex. native field address1_line1 for street 1 field)

**Comment by AndrewButenko** [comment]
@SyvokonSergey, this issue was reported before - https://github.com/AndrewButenko/CompositeAddress_PCF/issues/1 and it's not an issue of my control - it's a bug of a platform.
Andrew

**Comment by SyvokonSergey** [comment]
Thx, Andrew,
You did a great job

BR
Sergey

**Comment by AndrewButenko** [comment]
@SyvokonSergey you are welcome!
