### ISSUE TITLE
Can't build a solution

### ISSUE THREAD

**Issue by SanketMantri** [a33ik/CompositeAddress_PCF#5]
I am trying to buid a solution from the code I have downloaded but I am getting the following error.
C:\Users\sanket\Desktop\pcf\onepcf\onepcf.cdsproj" (build target) (1:7) ->
(ProcessCdsProjectReferencesOutputs target) ->
  C:\Users\sanket\.nuget\packages\microsoft.powerapps.msbuild.solution\1.0.6\build\Microsoft.PowerApps.MSBuild.Solution
.targets(98,5): error : Project Reference with output path 0, is not a valid PowerApps Component Type  [C:\Users\sanket
\Desktop\pcf\onepcf\onepcf.cdsproj]
  C:\Users\sanket\.nuget\packages\microsoft.powerapps.msbuild.solution\1.0.6\build\Microsoft.PowerApps.MSBuild.Solution
.targets(98,5): error : Cds component type  not supported [C:\Users\sanket\Desktop\pcf\onepcf\onepcf.cdsproj]

I am following this tutorial to build the solution:
https://www.youtube.com/watch?v=2uO2L2xTPkc

If there is any other way to install this component to PowerApps please let me know.

**Comment by AndrewButenko** [comment]
Hello,
If you're getting errors - you're doing something wrong and I can't tell what exactly).
You can download solution that you can install here - https://github.com/AndrewButenko/CompositeAddress_PCF/releases/tag/1.0.0.0
Thanks,
Andrew
