### ISSUE TITLE
Address Composite field showing up after exiting screen

### ISSUE THREAD

**Issue by tgiard2020** [a33ik/CompositeAddress_PCF#9]
![Address](https://user-images.githubusercontent.com/64980087/84852743-305d8280-b023-11ea-8b72-783f13ae18a7.PNG)

Hello,
When I open up the composite address field and then exit out of the form without clicking the composite address field a 2nd time, the address field continues to show up despite no longer being in the form (See screenshot).  Is there a way to avoid this?

Thanks!

**Comment by AndrewButenko** [comment]
Hello,
I work on React version of the same control that will not have this bug so... stay tuned :)
Andrew

**Comment by tgiard2020** [comment]
Thanks! I have one more question for you if you don't mind: Is it possible to make the fields inside this composite address "read only"? I have a flow that auto-populates the street, city, etc., and would love to be able to make it so users cannot the text.

**Comment by xairrick** [comment]
This can be fixed by hiding the popover in the destroy event  
```
public destroy(): void {
    // Add code to cleanup control if necessary
    $(this.mainAddressField).popover("hide");
}
```

Now if I only knew where to hook this into when a different field on the form is selected

**Comment by AndrewButenko** [comment]
@xairrick thanks for that! I will release new react-based control soon where this issues doesn't exist. So just wait for it :)

**Comment by xairrick** [comment]
FWIW, i was able to have it close the popover when it lost focus.   Changes can be found in fork -> https://github.com/xairrick/CompositeAddress_PCF

**Comment by tgiard2020** [comment]
Sorry, completely forgot to reply here. Thank you all for the help! I'll close this issue.
